modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
    modId = "fishlog"
    version = "${version}"
    displayName = "FishLog"
    description = "Détecte les prises en chat, log CSV, affiche les stats en jeu."

[[dependencies.fishlog]]
    modId = "forge"
    mandatory = true
    versionRange = "[52,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.fishlog]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "CLIENT"
