modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "fishlog"
    version = "${version}"
    displayName = "FishLog"
    description = "Détecte les prises en chat, log CSV, affiche les stats en jeu."

[[dependencies.fishlog]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.fishlog]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "CLIENT"
